resolver: lts-8.13
compiler: ghc-8.0.2

packages:
- '.'

extra-deps:
- spiros-0.0.0
- enumerate-0.2.2

- fltkhs-0.5.4.1
- text-1.2.2.0
# - prettyprinter-1.1.1
- lens-aeson-1.0.2
- generic-lens-0.4.1.0
- unification-fd-0.10.0.1
- frisby-0.2.1

# resolver: lts-9.12
# compiler: ghc-8.0.2

# packages:
# - ./
# # - ~/spiros

# extra-deps: 
# - spiros-0.0.0

flags: 
  fltkhs: 
    bundled: true 
