resolver: lts-8.13
compiler: ghc-8.0.2

packages:
- '.'

extra-deps:
- spiros-0.0.0

- fltkhs-0.5.4.1
- text-1.2.2.0
- async-pool-0.9.0.2
- prettyprinter-1.1.1
- lens-aeson-1.0.2

# resolver: lts-9.12
# compiler: ghc-8.0.2

# packages:
# - ./
# # - ~/spiros

# extra-deps: 
# - spiros-0.0.0

flags: 
  fltkhs: 
    bundled: true 